# Generated by Django 5.1.4 on 2025-01-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_rename_created_at_order_placed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
