# Generated by Django 5.1.4 on 2025-01-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_rename_customer_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
