# Generated by Django 5.1.4 on 2025-01-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='last_update',
        ),
    ]
